#!/bin/bash

# Enable experimental flag
echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json
sudo systemctl restart docker

# Register qemu-*-static
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

