name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Experimental Status
        run: |
          docker version -f '{{.Server.Experimental}}'

      - name: Experimental Setup
        run: |
          echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
          docker version -f '{{.Server.Experimental}

      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker build . --file Dockerfile --tag evi0s/armtorch:1.5.1
